[book]
authors = ["Thomas Powers"]
language = "en"
multilingual = false
src = "src"
description = "Explanation of Kukai Indexer Dependencies."
title = "Kukai Indexer Dependencies"

[output.html]
theme = "src/theme"
default-theme = "rust"
# default-theme = "ayu"

# [output.epub]

[output.html.search]
limit-results = 15

[rust]
edition = "2018"

[build]
build-dir = "dist"
create-missing = false

[preprocessor.index]
[preprocessor.links]

